[package]
name = "nightmare"
version = "1.0.0"
authors = ["Nat5"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
